apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: mongodb
  namespace: ls-system
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: ghcr.io/vasu1124/ocm
      componentName: mongodb.org/mongodb
      version: 8.0.16

  blueprint:
    ref:
      resourceName: mongodb-blueprint

  imports:
    targets:
    - name: cluster
      # the "#" forces the landscaper to use the target with the name in the same namespace
      target: "#default"

  importDataMappings:
    namespace: mongodb
    rootPassword: some-secret-password

  exports:
    data:
    - name: connection
      dataRef: "mongodb-connection"
