apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: etcd
  namespace: ls-system
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: ghcr.io/vasu1124/ocm
      componentName: etcd.io/etcd
      version: v3.6.6

  blueprint:
    ref:
      resourceName: etcd-blueprint

  imports:
    targets:
    - name: cluster
      # the "#" forces the landscaper to use the target with the name in the same namespace
      target: "#default"

  importDataMappings:
    namespace: etcd
    rootPassword: some-secret-password
    replicaCount: 3
